### PR TITLE
Add russian version of README

### PR DESCRIPTION
**Pull request by JustMarkov**
Hello, I have translated the README file into Russian language and added a button to switch between locales.  
I've translated the «Terrible» badge, but didn't change the logo, as I don't have any sources of it. If you can provide any (just the background would be enough), then I can adopt it too.

### CODE REVIEW

**Comment by zenfyrdev** [comment]
I can send the figma template for that badge.

**Review by melontini — CHANGES_REQUESTED** [review]
Could you please move the file from `README_ru.md` to `ru/README.md`?

**Comment by DancingEmptier667** [comment]
> I can send the figma template for that badge.

That would be awesome.

> Could you please move the file from `README_ru.md` to `ru/README.md`?

Done.

**Comment by zenfyrdev** [comment]
[devinsbadges-template (Copy).zip](https://github.com/melontini/bootloader-unlock-wall-of-shame/files/15498949/devinsbadges-template.Copy.zip)

Wait, did you mean the banner?

**Comment by melontini** [comment]
bwof_banner_small_empty
bwof_banner_small_key_only
key


The font is https://fonts.google.com/specimen/Kanit, but it doesn't support cyrillic.

**Comment by DancingEmptier667** [comment]
> [devinsbadges-template (Copy).zip](https://github.com/melontini/bootloader-unlock-wall-of-shame/files/15498949/devinsbadges-template.Copy.zip)
> 
> Wait, did you mean the banner?

Yes 😅

> The font is https://fonts.google.com/specimen/Kanit, but it doesn't support cyrillic.

I'll try to find similiar one, thanks!

**Comment by DancingEmptier667** [comment]
Everything's done now.
I adapted the banner, included all the 3 adapted images into the main repo and updated Russian README.md.

**Review by melontini — APPROVED** [review]
Looks good, thank you.

**Pull request merged**
