### PR TITLE
Samsung: add some additional info

### PR DESCRIPTION
**Pull request by Lost-Entrepreneur439**

### CODE REVIEW

**Review by melontini — APPROVED** [review]

**Comment by mirh** [comment]
I feel like it's not fair to put together apple-like devices with "you can unlock, but something breaks" (especially considering you still nonetheless have the [freedom](https://github.com/salvogiangri/KnoxPatch/issues/53) to fix it). 
Also.. What in the heaven even is the relationship between exynos modems having proprietary volte, and bootloader unlock?

p.s. some links are broken

**Comment by zenfyrdev** [comment]
> "you can unlock, but something breaks" (especially considering you still nonetheless have the https://github.com/salvogiangri/KnoxPatch/issues/53 to fix it).

You shouldn't have to. The problem is that it's broken on purpose, and the end user shouldn't have to do that.

> Also.. What in the heaven even is the relationship between exynos modems having proprietary volte, and bootloader unlock?

Nothing. This is just an example of how Samsung works against custom OS users.

IMHO, telling people to "proceed with caution" when a company has already shown it's willing to break completely unrelated features in retaliation is a bad practice.

> p.s. some links are broken

Strange. I'll look into it, thank you.

**Comment by mirh** [comment]
> You shouldn't have to. The problem is that it's broken on purpose, and the end user shouldn't have to do that.

Yes and no. I'll grant that I really cannot understand why camera is special here (and I agree that its breakage ***IS*** a notch less than "proceed with caution"), but for everything else it's pretty much always:
* app guys decide to add various knox dependencies here and there because muy sandbox and security to brag about
* bootloader guy has the whole knox tripped when unlocking

> This is just an example of how Samsung works against custom OS users.

Not at all? It seems [actually](https://github.com/jameskdev/android_samsung_imsservice#shenanigans-behind-samsungs-ims-services) just that their proprietary IMS service isn't a drop-in replacement of the aosp one (which I also [understand](https://news.ycombinator.com/item?id=38619978) now to be proprietary, lol, and to suck royally all around android land). 
And putting aside that whatever the fix here [wouldn't](https://xdaforums.com/t/gsi-14-lineageos-21-trebledroid-based.4654132/page-10#post-89537437) just be an annoying workaround just for Samsung's sake (unlike the camera, which I again agree to be important), regardless I'm still not sure what this has to do with booloader unlocking.

> break completely unrelated features in retaliation is a bad practice.

Never attribute to malice that which is adequately explained by stupidity. I still remember when sony greatest new XZ something broke camera on unlock, because with the advent of a new sensor generation somebody (I assume from their exmor/semiconductor division) had gotten the great idea of adding DRM-specific features.. not just into the camera app, but into the camera driver itself. 
It was eventually addressed (cannot remember if those that had already unlocked the phone could get away with it), but certainly you could never have argued this was to spite the [community](https://github.com/sonyxperiadev/kernel) they so much invest in to this day.

**Comment by mirh** [comment]
https://www.xda-developers.com/bootloader-unlocking-no-longer-kills-galaxy-z-fold-3-cameras/
https://www.xda-developers.com/samsung-galaxy-s22-bootloader-unlock-camera-working/
And I can guess the thread link is down because it was deleted after turning into a non-issue.

**Comment by zenfyrdev** [comment]
My apologies, I forgot about this. Thanks for the source on the camera thing. I'll update the camera and volte sections when I feel a bit better. I'll also think about moving it down to PWC

**Comment by mirh** [comment]
I mean, it should still remain in the worst category, as far as the US variants are concerned ([apparently](https://xdaforums.com/t/can-anyone-confirm-bootloader-unlock-of-s22-international-snapdragon-e-or-0.4441295/) it's not a matter of cpu)

Though I am still having scruples about the lack of some distinguishing feature between "bad devices" and "apple-like cancer" tbh.

**Comment by mirh** [comment]
Friendly ping for PWC imho.

Also hats off for the new "cancer" category.. though I feel like "🍅 Just terrible!" and "⛔ Avoid at all costs!" is actually kinda unclear (if I didn't know better, just with the label I'd think the order of preference is reversed).
p.s. I feel like you may have missed HTC
p.p.s and asus's last [admission](https://www.androidpolice.com/thread/asus-wont-support-bootloader-unlocking-anymore/)

**Pull request merged**
