### PR TITLE
Redo OnePlus

### PR DESCRIPTION
**Pull request by madeline-yana**

### CODE REVIEW

**Review by melontini — CHANGES_REQUESTED** [review]
The problem with OnePlus is that they used to offer their own Deep Testing for SIM-locked devices in the US, but it's no longer available.

They should still stay in PCD, but closer to the bottom.

**Comment by madeline-yana** [comment]
> The problem with OnePlus is that they used to offer their own Deep Testing for SIM-locked devices in the US, but it's no longer available.
> 
> They should still stay in PCD, but closer to the bottom.

Alright

**Comment by madeline-yana** [comment]
The changes should've been automatically added to my pull request; check to see if you're good with it now

**Review by melontini — APPROVED** [review]
Looks fine now.

**Pull request merged**
